"""
Part 4 – Export Pipeline: Multi-format research report exporter.

Supports:
- PDF  (via weasyprint HTML→PDF)
- PPTX (via python-pptx)
- DOCX (via python-docx)
- Markdown (plain text download)
- Checklist (LLM-generated action items)
"""

import asyncio
import io
import logging
import re
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


class ResearchExporter:
    """
    Export research results to multiple formats.
    """

    def __init__(self, llm_client=None):
        self.llm = llm_client

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def export(
        self,
        fmt: str,
        report: str,
        sources: List[Dict[str, Any]],
        query: str = "",
        trust_metrics: Optional[Dict] = None,
        claims: Optional[List[Dict]] = None,
        comparison: Optional[Dict] = None,
    ) -> io.BytesIO:
        """
        Export research to the requested format.

        Returns an in-memory BytesIO buffer with the file contents.
        """
        if fmt == "pdf":
            return await self._export_pdf(report, sources, query, trust_metrics)
        elif fmt == "pptx":
            return await self._export_pptx(report, sources, query, trust_metrics)
        elif fmt == "docx":
            return await self._export_docx(report, sources, query, trust_metrics)
        elif fmt == "markdown":
            return self._export_markdown(report, sources, query, trust_metrics)
        elif fmt == "checklist":
            return await self._export_checklist(report, query)
        else:
            raise ValueError(f"Unsupported export format: {fmt}")

    # ------------------------------------------------------------------
    # Markdown (always available, no extra deps)
    # ------------------------------------------------------------------

    def _export_markdown(
        self,
        report: str,
        sources: List[Dict],
        query: str,
        trust_metrics: Optional[Dict],
    ) -> io.BytesIO:
        lines = [f"# Research Report: {query}\n"]

        if trust_metrics:
            lines.append("## Trust Metrics\n")
            lines.append(f"- Confidence Score: {trust_metrics.get('confidence_score', 'N/A')}")
            lines.append(f"- Sources Analyzed: {trust_metrics.get('sources_analyzed', 'N/A')}")
            lines.append(f"- Claims Verified: {trust_metrics.get('claims_verified', 0)}/{trust_metrics.get('claims_total', 0)}")
            lines.append(f"- Bias Risk: {trust_metrics.get('bias_risk', 'N/A')}\n")

        lines.append("## Report\n")
        lines.append(report)
        lines.append("\n\n## Sources\n")
        for i, src in enumerate(sources, 1):
            url = src.get("url", "")
            title = src.get("title", url)
            lines.append(f"{i}. [{title}]({url})")

        lines.append(f"\n\n---\n*Generated by Deep Research Agent*\n")

        buf = io.BytesIO()
        buf.write("\n".join(lines).encode("utf-8"))
        buf.seek(0)
        return buf

    # ------------------------------------------------------------------
    # PDF via weasyprint
    # ------------------------------------------------------------------

    async def _export_pdf(
        self,
        report: str,
        sources: List[Dict],
        query: str,
        trust_metrics: Optional[Dict],
    ) -> io.BytesIO:
        try:
            from weasyprint import HTML  # type: ignore
        except ImportError:
            logger.warning("weasyprint not installed; falling back to markdown")
            return self._export_markdown(report, sources, query, trust_metrics)

        html = self._build_html(report, sources, query, trust_metrics)

        def _render():
            buf = io.BytesIO()
            HTML(string=html).write_pdf(buf)
            buf.seek(0)
            return buf

        return await asyncio.to_thread(_render)

    # ------------------------------------------------------------------
    # PPTX via python-pptx
    # ------------------------------------------------------------------

    async def _export_pptx(
        self,
        report: str,
        sources: List[Dict],
        query: str,
        trust_metrics: Optional[Dict],
    ) -> io.BytesIO:
        try:
            from pptx import Presentation  # type: ignore
            from pptx.util import Inches, Pt  # type: ignore
        except ImportError:
            logger.warning("python-pptx not installed; falling back to markdown")
            return self._export_markdown(report, sources, query, trust_metrics)

        def _build():
            prs = Presentation()
            prs.slide_width = Inches(13.33)
            prs.slide_height = Inches(7.5)

            # Title slide
            slide = prs.slides.add_slide(prs.slide_layouts[0])
            slide.shapes.title.text = f"Research: {query[:60]}"
            slide.placeholders[1].text = "Generated by Deep Research Agent"

            # Trust metrics slide
            if trust_metrics:
                slide = prs.slides.add_slide(prs.slide_layouts[1])
                slide.shapes.title.text = "Trust Metrics"
                body = slide.placeholders[1]
                body.text = (
                    f"Confidence: {trust_metrics.get('confidence_score', 'N/A')}\n"
                    f"Sources: {trust_metrics.get('sources_analyzed', 0)}\n"
                    f"Claims: {trust_metrics.get('claims_verified', 0)}/{trust_metrics.get('claims_total', 0)}\n"
                    f"Bias Risk: {trust_metrics.get('bias_risk', 'N/A')}"
                )

            # Report slides (split by headings or every ~800 chars)
            chunks = self._chunk_report(report, max_chars=800)
            for i, chunk in enumerate(chunks):
                slide = prs.slides.add_slide(prs.slide_layouts[1])
                slide.shapes.title.text = f"Findings ({i + 1}/{len(chunks)})"
                slide.placeholders[1].text = chunk

            # Sources slide
            slide = prs.slides.add_slide(prs.slide_layouts[1])
            slide.shapes.title.text = "Sources"
            src_text = "\n".join(
                f"{i}. {s.get('title', s.get('url', ''))}"
                for i, s in enumerate(sources[:15], 1)
            )
            slide.placeholders[1].text = src_text or "No sources"

            buf = io.BytesIO()
            prs.save(buf)
            buf.seek(0)
            return buf

